### ISSUE TITLE
"Any" assignment is not working

### ISSUE THREAD

**Issue by Reconfirefly** [the-via/releases#12]
I am unable to add keycodes to my board use the red Any button. I was trying to add LT(1,KC_BSPC), and after some troubleshooting, even something simple like KC_L was not working. I've tried on 1.2.4 and 1.2.6. The key is just remapped to LSHIFT instead.

**Comment by Wilba6582** [comment]
I think this is a bug due to "Allow remapping via keyboard" in settings page. Turn that off to enter advanced keycodes.

**Comment by Reconfirefly** [comment]
Yep, that does the trick. Working on 1.2.7

**Comment by Wilba6582** [comment]
Reopening because it's still a bug we need to fix :P

**Comment by csarmendariz** [comment]
I think this bug is related to the problems with the "Any" button described in this issue: https://github.com/the-via/keyboards/issues/280

With ubuntu and 1.3.1, if I have "Allow remapping via keyboard" on, when I try to type anything into an "Any" key it actually modifies the keyboard layout instead of editing the content of the "Any" key.

In my case It was solved by turning "Allow remapping via keyboard" off.

**Comment by vurtomatic** [comment]
I think this still isn't working.

I'm on a Mac, have tried the latest v1.3.1 and rolled back up to v1.2.6.

"Allow remapping via keyboard" has been disabled, I also re-enabled and disabled again to no effect.

**Comment by jkomusin** [comment]
One small breakthrough I've had on this issue is that while the LCTL_T(KC_ESC) mod-tap doesn't work (blocking me from comfortably using VIA) changing to the long-form MT(MOD_LCTL, KC_ESC) does indeed work.

This is mentioned here: https://github.com/the-via/releases/issues/50#issuecomment-744112247
